name: Build Switch Module

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container: devkitpro/devkita64:latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Build module
      run: |
        make
        
    - name: Upload artifacts
      uses: actions/upload-artifact@v3
      with:
        name: switch-module
        path: |
          output/atmosphere/contents/0100000000000000/exefs/main
          atmosphere/contents/0100000000000000/flags/boot2.flag